name: Build
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '1 2 5 * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Prepare OCaml environment
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential git ocaml-nox ocaml-findlib libcamlpdf-ocaml-dev
          version: 1.0
      - name: Build
        run: make
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: cpdfsqueeze
  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
